import { Route } from "@/types/routes.type";

export const currentRoute: Route = {
  id: 44,
  tenant_id: 2,
  route_name: "Dec 1",
  depot_id: 1,
  job_ids: [2, 5, 6],
  team_member_ids: [1, 2, 6],
  scheduled_date: "2025-12-02",
  optimization_goal: "minimum_time",
  status: "completed",
  started_at: "2025-12-01T13:58:23.713562+05:30",
  completed_at: "2025-12-01T13:59:00.675649+05:30",
  error_message: null,
  result: {
    routes: [
      {
        stops: [
          {
            job_id: 2,
            stop_type: "job",
            arrival_time: "2025-12-02T13:56:07",
            latitude: 37.7749,
            longitude: -122.4194,
          },
          {
            job_id: 6,
            stop_type: "job",
            arrival_time: "2025-12-02T14:46:02",
            latitude: 37.7849,
            longitude: -122.4094,
          },
          {
            job_id: 5,
            stop_type: "job",
            arrival_time: "2025-12-02T18:48:45",
            latitude: 37.7649,
            longitude: -122.4294,
          },
          {
            job_id: 7,
            stop_type: "job",
            arrival_time: "2025-12-02T20:48:45",
            latitude: 37.7549,
            longitude: -122.4394,
          },
        ],
        vehicle_id: 3,
        route_polyline:
          "kzfkCawnyLyGOF[PMnAWFC@IOo@i@kBYqACOAU?O@_@XEhGeH_DiC{C_Fu@{@Uu@rAy@fAi@f@YzAu@fA]~@a@PCYm@Tu@Bo@Uk@bAsBz@{DL{@\\uCHcAkAQf@}CRq@SSa@c@OUOIOi@KcBI_@Qo@IKEGSKKADe@CMw@_AIOAMAMBM@EV_@BMBOKSYs@IgAGyCBo@I_C@UCyBRsANyAiE[sBW_BIu@uJi@FeAyDaBl@Ou@kAeEI]CUC}AM{DAeGImCB@b@SVG}AaJ}DsTkFuXs@}CmGeRkBuEm@KYAUi@Ue@dKuGbYqQfFeDVj@bFrLl@nAfCtD`BtBxApBnBrCxAlBhAExCUtCuAzBs@nB?hBW|@IlAZjAf@bAdAvBnAvAf@~@^dBoHBS`DD\\ARL?G@CDC@U`ELLcEBcBF{AL@fAHnAHp@ABsAHiAhAaC|CwEjByGbBgOAcC[mF@_Hb@uDd@qC`DsMqBm@`BkF`BqHx@m@pCaCp@yCFmD@qE]cHMaFkA_LaAgC_B}CcB{EV_DNsEr@_FNkBFkDAuCEmAYeCaAgCGaB[}Bk@oC[uAU_DB[GmCF{C?uCc@{DKmCMkCW_Do@qB@Y~A_AOu@vFaCm@qB@{Au@Xs@RmCmIGIyAwDg@b@g@w@IODm@FG@UfC{QoBBUMWuBEMKEqEVW?OGM_@i@}E_AeGa@H[FEkAC_@Mw@QgCGM]YyBqBaBaBa@e@g@{@NU@UEOe@y@l@_@s@sCK@}B}K_@wAsC|@c@uAEAGI]}Ao@gCUo@]Ts@kBkAaDgAiCYm@AG@GN]f@_ARa@dCgE^i@Z_@vCeHjA}Cp@cBhBwCj@w@~AoFjAiENk@XcBrCh@d@LhATQjAPkAiAUe@MsCi@YbBOj@kAhE_BnFeAa@mDeBkFq@oASIRSd@MTSXgB~BwAtBmB`CiAnA}@t@yBbBoAjAw@h@uBAgOSS@i@?_@IeMYgDMsXs@eAAKG[Bm@Bi@CAFW|DQfAI\\@VuAfJiBbKi@zDO`BStCg@nGExAB`FYjG@tA@zFKfFCbCSRoATc@JoHxCYRM^C^?dBClAEVSVYFe@@{C?wBFUrEIlBe@Ck@BsABq@YCRoAzEqBjEa@Ar@vC@LuAKeFaAg@hC}CDQdBGx@Kj@o@jBgAjCUDe@EmASaB[wCk@w@GU@a@CwCK}AFqAF}@\\oAj@oAb@gCx@A}@e@DSHs@DkAFMoCoHPGB]BCDA@G?ECg@@KCcD?_DMkB?iBIsASeA[sBu@s@e@{Ac@aAKcAAsA\\QJ?FCBA@E??BLfBAj@C\\YFoC\\g@d@MOmA^DlAeBO}Ck@YhCq@xAaAfBqBUQxAUdASL?XDFa@~AUz@EbAI`@[tAN?_@f@gA|@g@TIQ_AB{FSeDD_@fDWbCCz@@x@DhDEd@Ot@El@u@bY?NExCAzBH\\R`@DXPr@Fn@EPVbGDbFj@nEsAVyCl@cCZOBoBNoH\\GHe@JA@CBG?EEWBKEiDGaC[w@QkA_@eAm@aB?k@Gi@Mi@Ey@CkABG?YSeBsAuEzF_CeCeCuBsC^m@FEFQCSBwAb@}HnA]`@y@jAc@f@m@vAw@nAy@jAm@v@u@x@i@f@cAx@QFk@P_Cn@_Bd@}Ah@sDrAeBh@kAZkBb@KT}@`Ao@r@u@r@q@t@g@z@Sl@Il@Ch@Bb@FL?RGPMDIAQ?_@J{AdD]j@kAlBo@n@kA`BSf@Kd@Bt@?PANEFE@ICMMMMS?QFUVkEdH{LpUa@l@OBYAyB[CbAGtAE~BEDGBEACCCG?CBGBCFADBBB@B?HEDGBEACCCG_@OeCqAyF_D_EmCqDeDsJeHqFsEaG{EmG}EkAp@uNgMOUCMm@Hw@Bo@IkDl@yDh@iBXsAVw@Eg@FcHhAoAX{@j@kAXuAPqB`@a@JgDdAiAV_ABsAb@uBfAcEbDiBnAyAjAcA`AqBdCgAnAiG|GmAdBI^o@fDIn@a@`Bc@xAg@{@sASkCg@IoAgAA?MaBMFaAeBK{@Y}@LcAKm@Uc@Gy@PmBd@uDl@mHdAaD\\k@Jk@\\EKsCn@sLfAcCJmAI}CpMy@nDcPaEC@G?CACGs@SiGyAyBq@cDeAy@o@[QcBgCy@o@m@_@m@OgA@aL^}CNq@Cy@Mu@Ys@a@k@q@oA}BuAsBo@s@yAmAmAgAw@e@wAs@cBm@kCo@cEg@g@CwB@yBNsAJwC^}Dj@{@D}@Ae@I_ASo@Wc@We@a@mCqCWUI_@{@{@_EcDWD[@i@I{Cm@wCe@u@IqCk@uGm@e@G}@?kBF_A@mCNeCJmGLaCN}@ABWGo@Mg@UMo@CKWGWFi@p@Qc@s@a@IKGMUIQGWi@DQBID[IKIc@KM?M@a@RMFI?GAc@WCGCKDg@[BeC?{@DaA@UG_@SaA[w@SsE}@WIEGAI@QFqAPkBF}AqAGyF_@QEEIB{@ZaHlAoOgBOy@OaBs@aAm@{BmBu@aASSwDeCa@a@a@g@u@o@EGIEsAkASK_Aw@}@i@sA}@g@Y_Cu@]QWQQWOc@i@HGQMQMOgDaD{@w@cDgByBqAoDaCsF_D_@OUGUC}@GYESI_@Uq@c@s@k@gCgC_@W{@e@{Au@QEOCi@?aBHMAKCKE[WsCcDKKWOs@W}B_AMEOCm@E_@GmBa@UEQAkBGkAIMEGGk@}@Y]MMOMMEOCSCgAGQCMEKGIE?Uy@oCEWEMIKOIa@KcASIFIB_KDeLHDmEi@CGACEUyAKsACg@WLI?K?}@IBQA[GS_BoAKIIOKy@CYAe@@]g@HYHa@N[LuALuBNK?g@AgBUaCi@mB]M?C_@A_@XoHHaDHAEaF@m@AWI}JBuCFm@t@wF@a@C_AE[i@cCKw@a@_J_@oECg@k@yJK}C_@{Em@oIc@kHIgAi@gLOuBUwCMsA]}Bq@}Dk@qCoByIe@_@OKKKO_@Qk@GIGEICKAq@AmBBKAKEYYIEi@EgA?eAC}@B_AFYH[NKFODi@FO@IAGGEO]eBWu@Yk@MQOMWKqBq@GEGKK]GIKEWGgBQo@Mk@Kq@Gk@KGCEGCKKu@Sy@GYYcAS]UWQQu@q@[WYOy@]WMCCCGKi@GOo@s@_@Yc@TcB|@OFQBaBPqE|@oCn@m@Jw@AaE?i@Fm@JmAf@WFYNg@\\WTQNELc@Fa@DmBJs@@aF_@]?a@CYDyCt@]FO@wBMmAGgBd@iFnAGq@eB^cAPaFl@iC\\?l@mBXoIpBODJWAUC[OaAEg@Aa@?g@FwB@qBiLgEkCy@_GcBWGWEc@JYCEASKWWMKIOqD}DSSs@k@w@e@kG}CyAdDIEoGiDhAmCsNwHOGQAWAOyC}BNY?UGuAq@aGeDFOmGiDy@jB_HwD}@vBuN_Iw@pBk@lA]h@QKaDvHoE_COt@]bC{@tGi@jDKZKTMP_@`@sBzAwEfAsA?{Fo@?_AAGIIPiABIDG}@S|@REFCHQhAHH@F?~@zFn@rA?vEgArB{A^a@LQJUJ[h@kDz@uG\\cCNu@DUpE`CxCcHPJ\\i@j@mAv@qBtN~H|@wBtGpDv@kBxGnDGN`GdDtAp@TFX?|BONxCV@P@NFrNvHiAlCnGhDvAgDvGdDv@d@r@j@RRpD|DHNLJVVRJD@XBb@KVDVF~FbBjCx@~K`EfA^r@PlCh@x@LlA^bCz@nBp@xDk@bASn@O|HqBNd@h@JpBJvBLNA\\GxCu@XE`@B\\?`F^r@AlBK`@Eb@GDMPOVUf@]XOVGlAg@l@Kh@G`E?v@@l@KnCo@pE}@`BQPCNGbB}@b@U^Xn@r@FNJh@BFBBVLx@\\XNZVt@p@PPTVR\\XbAFXRx@Jt@BJDFFBj@Jp@Fj@Jn@LfBPVFJDFHJ\\FJFDxAd@VJVJNLLPXj@Vt@\\dBDNFFH@NAh@GNEJGZOXI~@G|@CdABfA?h@DHDXXJDJ@lBCp@@J@HBFDFHPj@N^JJNJd@^nBxIj@pCp@|D\\|BLrATvCNtBh@fLHfAb@jHl@nI^zEJ|Cn@`L^nE`@~IJv@h@bCDZB~@A`@u@vFGl@CtCH|J@VAl@D`FLAWxES~F?PBh@lB\\`Ch@fBTf@@J?tBOtAMZM`@OXIf@IA\\@d@BXJx@HNJH~AnAFR@ZCP|@HJ?H?VMBf@JrATxABDF@x@BElEtKI~JEHCHGbAR`@JNHHJDLDVx@nC?THDJFLDPBfAFRBNBLDNLLLX\\j@|@FFLDjAHjBFP@TDlB`@^Fl@DNBLD|B~@r@VVNJJrCbDZVJDJBL@`BIh@?NBPDzAt@z@d@^VfCfCr@j@p@b@^TRHXD|@FTBTF^NrF~CnD`CxBpAbDfBz@v@fD`DLNLPFPh@INb@PVVP\\P~Bt@f@XrA|@|@h@~@v@RJrAjAHDDFt@n@`@f@`@`@vDdCRRt@`AzBlB`Al@`Br@x@NfBNmAnO[`HCz@DHPDxF^pAFG|AQjBGpAAP@HDFVHrE|@v@R`AZ^RTF`AAz@EdC?ZCEf@BJBFb@VF@H?LG`@SLAL?b@JJHZHHEPCh@EFVHPLTJF`@Hb@r@q@PGh@FVJVn@BTLLf@Fn@CV|@@`COlGMdCKlCO~@AjBG|@?d@FtGl@pCj@t@HvCd@zCl@h@HZAVE~DbDz@z@RFXXv@r@a@vHK~@SlAxNpB^\\bAt@n@RxGbBnGzA|Ad@^RhBn@~FtAnLtClFxA^D|Ec@dEeAlCGfAIlBGLGlD@VFj@GDSbDdAtCx@bHhBH?DD?BfPvDpBf@vBj@`FxAxFzAxGhBFLxAfAjG|GVf@XQj@l@RJVBP?LEPMBRBJrEzByAtDORGDI@xA`@nAXZD^BpACRDPBhDMv@EFVDXDnAiA`@xBnJxC~F`AjC~AjATDXt@z@dF~UeA\\CzEA|BCHGBSb@Cj@Vf@TbANXjDnNy@nBOtAfF~@tDj@|@rAy@`K~Zn@|B`HlTZv@DFHBtCn@vEr@h@LJ@`Ep@xLzBdDr@`Dh@hIdBfI~AjI|A|NzCjIzB~KvDrG~BLNPNLH|H~CdIxCfBgFxA^^T|CtAfC|@|L|EHY~G`CfLxEn@gB`Bt@lAf@tEdAVBH@zAEtAGlCWzCO`BBxB@lDFnANRExDKp@?HDnBBpACvBG~EEd@?\\APCFCVUXOBGPM^Er@Gv@Sj@WlBk@d@IP@`COv@Ml@QlBs@pAk@XSRKNQx@]d@Mj@Gd@A^@FDX?\\@n@AzAInCQlBUlA[rDgArBk@p@SPKLEfAc@~CoA\\Ox@Oz@Ep@?|AFvC@rAFd@EnCGYyEAS^Dj@@@PJ~Dd@H`@APAZEbBKn@Kl@m@JNLDvDK~BCpCPx@h@b@^h@|@l@\\TNTTTXPDLIB?FB\\NPJBFl@V@?DCHGPDD?\\ApABT?NAVKPKCELIBD~BvD^j@l@`AtBtClHlIDADBBB@FADABdClCl@lACbJDXFVxC_Af@GjBCfGLb@Bt@DVHxAv@dAr@bBrAf@ZZBx@RnA`@Jv@b@~BbExArC~@lDjANDjBX`BFlAF|BZ`AJnCB`@Cx@f@bA?fBXfA`@x@n@PP~AdAn@r@bArAK`AXr@ZL^\\NR?fADh@?~@Ch@Gb@SdA~DaA~BMTnB@pDChB`IP",
        team_member_id: 2,
        team_member_name: "second driver",
        total_distance_meters: 89454221,
        total_duration_seconds: 89564542,
      },
      {
        stops: [
          {
            job_id: 2,
            stop_type: "job",
            arrival_time: "2025-12-02T09:00:07",
            latitude: 37.7749,
            longitude: -122.4194,
          },
          {
            job_id: 6,
            stop_type: "job",
            arrival_time: "2025-12-02T14:46:02",
            latitude: 37.7849,
            longitude: -122.4094,
          },
          {
            job_id: 5,
            stop_type: "job",
            arrival_time: "2025-12-02T23:48:45",
            latitude: 37.7649,
            longitude: -122.4294,
          },
        ],
        vehicle_id: 3,
        route_polyline:
          "kzfkCawnyLyGOF[PMnAWFC@IOo@i@kBYqACOAU?O@_@XEhGeH_DiC{C_Fu@{@Uu@rAy@fAi@f@YzAu@fA]~@a@PCYm@Tu@Bo@Uk@bAsBz@{DL{@\\uCHcAkAQf@}CRq@SSa@c@OUOIOi@KcBI_@Qo@IKEGSKKADe@CMw@_AIOAMAMBM@EV_@BMBOKSYs@IgAGyCBo@I_C@UCyBRsANyAiE[sBW_BIu@uJi@FeAyDaBl@Ou@kAeEI]CUC}AM{DAeGImCB@b@SVG}AaJ}DsTkFuXs@}CmGeRkBuEm@KYAUi@Ue@dKuGbYqQfFeDVj@bFrLl@nAfCtD`BtBxApBnBrCxAlBhAExCUtCuAzBs@nB?hBW|@IlAZjAf@bAdAvBnAvAf@~@^dBoHBS`DD\\ARL?G@CDC@U`ELLcEBcBF{AL@fAHnAHp@ABsAHiAhAaC|CwEjByGbBgOAcC[mF@_Hb@uDd@qC`DsMqBm@`BkF`BqHx@m@pCaCp@yCFmD@qE]cHMaFkA_LaAgC_B}CcB{EV_DNsEr@_FNkBFkDAuCEmAYeCaAgCGaB[}Bk@oC[uAU_DB[GmCF{C?uCc@{DKmCMkCW_Do@qB@Y~A_AOu@vFaCm@qB@{Au@Xs@RmCmIGIyAwDg@b@g@w@IODm@FG@UfC{QoBBUMWuBEMKEqEVW?OGM_@i@}E_AeGa@H[FEkAC_@Mw@QgCGM]YyBqBaBaBa@e@g@{@NU@UEOe@y@l@_@s@sCK@}B}K_@wAsC|@c@uAEAGI]}Ao@gCUo@]Ts@kBkAaDgAiCYm@AG@GN]f@_ARa@dCgE^i@Z_@vCeHjA}Cp@cBhBwCj@w@~AoFjAiENk@XcBrCh@d@LhATQjAPkAiAUe@MsCi@YbBOj@kAhE_BnFeAa@mDeBkFq@oASIRSd@MTSXgB~BwAtBmB`CiAnA}@t@yBbBoAjAw@h@uBAgOSS@i@?_@IeMYgDMsXs@eAAKG[Bm@Bi@CAFW|DQfAI\\@VuAfJiBbKi@zDO`BStCg@nGExAB`FYjG@tA@zFKfFCbCSRoATc@JoHxCYRM^C^?dBClAEVSVYFe@@{C?wBFUrEIlBe@Ck@BsABq@YCRoAzEqBjEa@Ar@vC@LuAKeFaAg@hC}CDQdBGx@Kj@o@jBgAjCUDe@EmASaB[wCk@w@GU@a@CwCK}AFqAF}@\\oAj@oAb@gCx@A}@e@DSHs@DkAFMoCoHPGB]BCDA@G?ECg@@KCcD?_DMkB?iBIsASeA[sBu@s@e@{Ac@aAKcAAsA\\QJ?FCBA@E??BLfBAj@C\\YFoC\\g@d@MOmA^DlAeBO}Ck@YhCq@xAaAfBqBUQxAUdASL?XDFa@~AUz@EbAI`@[tAN?_@f@gA|@g@TIQ_AB{FSeDD_@fDWbCCz@@x@DhDEd@Ot@El@u@bY?NExCAzBH\\R`@DXPr@Fn@EPVbGDbFj@nEsAVyCl@cCZOBoBNoH\\GHe@JA@CBG?EEWBKEiDGaC[w@QkA_@eAm@aB?k@Gi@Mi@Ey@CkABG?YSeBsAuEzF_CeCeCuBsC^m@FEFQCSBwAb@}HnA]`@y@jAc@f@m@vAw@nAy@jAm@v@u@x@i@f@cAx@QFk@P_Cn@_Bd@}Ah@sDrAeBh@kAZkBb@KT}@`Ao@r@u@r@q@t@g@z@Sl@Il@Ch@Bb@FL?RGPMDIAQ?_@J{AdD]j@kAlBo@n@kA`BSf@Kd@Bt@?PANEFE@ICMMMMS?QFUVkEdH{LpUa@l@OBYAyB[CbAGtAE~BEDGBEACCCG?CBGBCFADBBB@B?HEDGBEACCCG_@OeCqAyF_D_EmCqDeDsJeHqFsEaG{EmG}EkAp@uNgMOUCMm@Hw@Bo@IkDl@yDh@iBXsAVw@Eg@FcHhAoAX{@j@kAXuAPqB`@a@JgDdAiAV_ABsAb@uBfAcEbDiBnAyAjAcA`AqBdCgAnAiG|GmAdBI^o@fDIn@a@`Bc@xAg@{@sASkCg@IoAgAA?MaBMFaAeBK{@Y}@LcAKm@Uc@Gy@PmBd@uDl@mHdAaD\\k@Jk@\\EKsCn@sLfAcCJmAI}CpMy@nDcPaEC@G?CACGs@SiGyAyBq@cDeAy@o@[QcBgCy@o@m@_@m@OgA@aL^}CNq@Cy@Mu@Ys@a@k@q@oA}BuAsBo@s@yAmAmAgAw@e@wAs@cBm@kCo@cEg@g@CwB@yBNsAJwC^}Dj@{@D}@Ae@I_ASo@Wc@We@a@mCqCWUI_@{@{@_EcDWD[@i@I{Cm@wCe@u@IqCk@uGm@e@G}@?kBF_A@mCNeCJmGLaCN}@ABWGo@Mg@UMo@CKWGWFi@p@Qc@s@a@IKGMUIQGWi@DQBID[IKIc@KM?M@a@RMFI?GAc@WCGCKDg@[BeC?{@DaA@UG_@SaA[w@SsE}@WIEGAI@QFqAPkBF}AqAGyF_@QEEIB{@ZaHlAoOgBOy@OaBs@aAm@{BmBu@aASSwDeCa@a@a@g@u@o@EGIEsAkASK_Aw@}@i@sA}@g@Y_Cu@]QWQQWOc@i@HGQMQMOgDaD{@w@cDgByBqAoDaCsF_D_@OUGUC}@GYESI_@Uq@c@s@k@gCgC_@W{@e@{Au@QEOCi@?aBHMAKCKE[WsCcDKKWOs@W}B_AMEOCm@E_@GmBa@UEQAkBGkAIMEGGk@}@Y]MMOMMEOCSCgAGQCMEKGIE?Uy@oCEWEMIKOIa@KcASIFIB_KDeLHDmEi@CGACEUyAKsACg@WLI?K?}@IBQA[GS_BoAKIIOKy@CYAe@@]g@HYHa@N[LuALuBNK?g@AgBUaCi@mB]M?C_@A_@XoHHaDHAEaF@m@AWI}JBuCFm@t@wF@a@C_AE[i@cCKw@a@_J_@oECg@k@yJK}C_@{Em@oIc@kHIgAi@gLOuBUwCMsA]}Bq@}Dk@qCoByIe@_@OKKKO_@Qk@GIGEICKAq@AmBBKAKEYYIEi@EgA?eAC}@B_AFYH[NKFODi@FO@IAGGEO]eBWu@Yk@MQOMWKqBq@GEGKK]GIKEWGgBQo@Mk@Kq@Gk@KGCEGCKKu@Sy@GYYcAS]UWQQu@q@[WYOy@]WMCCCGKi@GOo@s@_@Yc@TcB|@OFQBaBPqE|@oCn@m@Jw@AaE?i@Fm@JmAf@WFYNg@\\WTQNELc@Fa@DmBJs@@aF_@]?a@CYDyCt@]FO@wBMmAGgBd@iFnAGq@eB^cAPaFl@iC\\?l@mBXoIpBODJWAUC[OaAEg@Aa@?g@FwB@qBiLgEkCy@_GcBWGWEc@JYCEASKWWMKIOqD}DSSs@k@w@e@kG}CyAdDIEoGiDhAmCsNwHOGQAWAOyC}BNY?UGuAq@aGeDFOmGiDy@jB_HwD}@vBuN_Iw@pBk@lA]h@QKaDvHoE_COt@]bC{@tGi@jDKZKTMP_@`@sBzAwEfAsA?{Fo@?_AAGIIPiABIDG}@S|@REFCHQhAHH@F?~@zFn@rA?vEgArB{A^a@LQJUJ[h@kDz@uG\\cCNu@DUpE`CxCcHPJ\\i@j@mAv@qBtN~H|@wBtGpDv@kBxGnDGN`GdDtAp@TFX?|BONxCV@P@NFrNvHiAlCnGhDvAgDvGdDv@d@r@j@RRpD|DHNLJVVRJD@XBb@KVDVF~FbBjCx@~K`EfA^r@PlCh@x@LlA^bCz@nBp@xDk@bASn@O|HqBNd@h@JpBJvBLNA\\GxCu@XE`@B\\?`F^r@AlBK`@Eb@GDMPOVUf@]XOVGlAg@l@Kh@G`E?v@@l@KnCo@pE}@`BQPCNGbB}@b@U^Xn@r@FNJh@BFBBVLx@\\XNZVt@p@PPTVR\\XbAFXRx@Jt@BJDFFBj@Jp@Fj@Jn@LfBPVFJDFHJ\\FJFDxAd@VJVJNLLPXj@Vt@\\dBDNFFH@NAh@GNEJGZOXI~@G|@CdABfA?h@DHDXXJDJ@lBCp@@J@HBFDFHPj@N^JJNJd@^nBxIj@pCp@|D\\|BLrATvCNtBh@fLHfAb@jHl@nI^zEJ|Cn@`L^nE`@~IJv@h@bCDZB~@A`@u@vFGl@CtCH|J@VAl@D`FLAWxES~F?PBh@lB\\`Ch@fBTf@@J?tBOtAMZM`@OXIf@IA\\@d@BXJx@HNJH~AnAFR@ZCP|@HJ?H?VMBf@JrATxABDF@x@BElEtKI~JEHCHGbAR`@JNHHJDLDVx@nC?THDJFLDPBfAFRBNBLDNLLLX\\j@|@FFLDjAHjBFP@TDlB`@^Fl@DNBLD|B~@r@VVNJJrCbDZVJDJBL@`BIh@?NBPDzAt@z@d@^VfCfCr@j@p@b@^TRHXD|@FTBTF^NrF~CnD`CxBpAbDfBz@v@fD`DLNLPFPh@INb@PVVP\\P~Bt@f@XrA|@|@h@~@v@RJrAjAHDDFt@n@`@f@`@`@vDdCRRt@`AzBlB`Al@`Br@x@NfBNmAnO[`HCz@DHPDxF^pAFG|AQjBGpAAP@HDFVHrE|@v@R`AZ^RTF`AAz@EdC?ZCEf@BJBFb@VF@H?LG`@SLAL?b@JJHZHHEPCh@EFVHPLTJF`@Hb@r@q@PGh@FVJVn@BTLLf@Fn@CV|@@`COlGMdCKlCO~@AjBG|@?d@FtGl@pCj@t@HvCd@zCl@h@HZAVE~DbDz@z@RFXXv@r@a@vHK~@SlAxNpB^\\bAt@n@RxGbBnGzA|Ad@^RhBn@~FtAnLtClFxA^D|Ec@dEeAlCGfAIlBGLGlD@VFj@GDSbDdAtCx@bHhBH?DD?BfPvDpBf@vBj@`FxAxFzAxGhBFLxAfAjG|GVf@XQj@l@RJVBP?LEPMBRBJrEzByAtDORGDI@xA`@nAXZD^BpACRDPBhDMv@EFVDXDnAiA`@xBnJxC~F`AjC~AjATDXt@z@dF~UeA\\CzEA|BCHGBSb@Cj@Vf@TbANXjDnNy@nBOtAfF~@tDj@|@rAy@`K~Zn@|B`HlTZv@DFHBtCn@vEr@h@LJ@`Ep@xLzBdDr@`Dh@hIdBfI~AjI|A|NzCjIzB~KvDrG~BLNPNLH|H~CdIxCfBgFxA^^T|CtAfC|@|L|EHY~G`CfLxEn@gB`Bt@lAf@tEdAVBH@zAEtAGlCWzCO`BBxB@lDFnANRExDKp@?HDnBBpACvBG~EEd@?\\APCFCVUXOBGPM^Er@Gv@Sj@WlBk@d@IP@`COv@Ml@QlBs@pAk@XSRKNQx@]d@Mj@Gd@A^@FDX?\\@n@AzAInCQlBUlA[rDgArBk@p@SPKLEfAc@~CoA\\Ox@Oz@Ep@?|AFvC@rAFd@EnCGYyEAS^Dj@@@PJ~Dd@H`@APAZEbBKn@Kl@m@JNLDvDK~BCpCPx@h@b@^h@|@l@\\TNTTTXPDLIB?FB\\NPJBFl@V@?DCHGPDD?\\ApABT?NAVKPKCELIBD~BvD^j@l@`AtBtClHlIDADBBB@FADABdClCl@lACbJDXFVxC_Af@GjBCfGLb@Bt@DVHxAv@dAr@bBrAf@ZZBx@RnA`@Jv@b@~BbExArC~@lDjANDjBX`BFlAF|BZ`AJnCB`@Cx@f@bA?fBXfA`@x@n@PP~AdAn@r@bArAK`AXr@ZL^\\NR?fADh@?~@Ch@Gb@SdA~DaA~BMTnB@pDChB`IP",
        team_member_id: 2,
        team_member_name: "second driver",
        total_distance_meters: 87568,
        total_duration_seconds: 62260,
      },
      {
        stops: [
          {
            job_id: 2,
            stop_type: "job",
            arrival_time: "2025-12-02T13:56:07",
          },
          {
            job_id: 6,
            stop_type: "job",
            arrival_time: "2025-12-02T14:46:02",
          },
          {
            job_id: 5,
            stop_type: "job",
            arrival_time: "2025-12-02T18:48:45",
          },
        ],
        vehicle_id: 3,
        route_polyline:
          "kzfkCawnyLyGOF[PMnAWFC@IOo@i@kBYqACOAU?O@_@XEhGeH_DiC{C_Fu@{@Uu@rAy@fAi@f@YzAu@fA]~@a@PCYm@Tu@Bo@Uk@bAsBz@{DL{@\\uCHcAkAQf@}CRq@SSa@c@OUOIOi@KcBI_@Qo@IKEGSKKADe@CMw@_AIOAMAMBM@EV_@BMBOKSYs@IgAGyCBo@I_C@UCyBRsANyAiE[sBW_BIu@uJi@FeAyDaBl@Ou@kAeEI]CUC}AM{DAeGImCB@b@SVG}AaJ}DsTkFuXs@}CmGeRkBuEm@KYAUi@Ue@dKuGbYqQfFeDVj@bFrLl@nAfCtD`BtBxApBnBrCxAlBhAExCUtCuAzBs@nB?hBW|@IlAZjAf@bAdAvBnAvAf@~@^dBoHBS`DD\\ARL?G@CDC@U`ELLcEBcBF{AL@fAHnAHp@ABsAHiAhAaC|CwEjByGbBgOAcC[mF@_Hb@uDd@qC`DsMqBm@`BkF`BqHx@m@pCaCp@yCFmD@qE]cHMaFkA_LaAgC_B}CcB{EV_DNsEr@_FNkBFkDAuCEmAYeCaAgCGaB[}Bk@oC[uAU_DB[GmCF{C?uCc@{DKmCMkCW_Do@qB@Y~A_AOu@vFaCm@qB@{Au@Xs@RmCmIGIyAwDg@b@g@w@IODm@FG@UfC{QoBBUMWuBEMKEqEVW?OGM_@i@}E_AeGa@H[FEkAC_@Mw@QgCGM]YyBqBaBaBa@e@g@{@NU@UEOe@y@l@_@s@sCK@}B}K_@wAsC|@c@uAEAGI]}Ao@gCUo@]Ts@kBkAaDgAiCYm@AG@GN]f@_ARa@dCgE^i@Z_@vCeHjA}Cp@cBhBwCj@w@~AoFjAiENk@XcBrCh@d@LhATQjAPkAiAUe@MsCi@YbBOj@kAhE_BnFeAa@mDeBkFq@oASIRSd@MTSXgB~BwAtBmB`CiAnA}@t@yBbBoAjAw@h@uBAgOSS@i@?_@IeMYgDMsXs@eAAKG[Bm@Bi@CAFW|DQfAI\\@VuAfJiBbKi@zDO`BStCg@nGExAB`FYjG@tA@zFKfFCbCSRoATc@JoHxCYRM^C^?dBClAEVSVYFe@@{C?wBFUrEIlBe@Ck@BsABq@YCRoAzEqBjEa@Ar@vC@LuAKeFaAg@hC}CDQdBGx@Kj@o@jBgAjCUDe@EmASaB[wCk@w@GU@a@CwCK}AFqAF}@\\oAj@oAb@gCx@A}@e@DSHs@DkAFMoCoHPGB]BCDA@G?ECg@@KCcD?_DMkB?iBIsASeA[sBu@s@e@{Ac@aAKcAAsA\\QJ?FCBA@E??BLfBAj@C\\YFoC\\g@d@MOmA^DlAeBO}Ck@YhCq@xAaAfBqBUQxAUdASL?XDFa@~AUz@EbAI`@[tAN?_@f@gA|@g@TIQ_AB{FSeDD_@fDWbCCz@@x@DhDEd@Ot@El@u@bY?NExCAzBH\\R`@DXPr@Fn@EPVbGDbFj@nEsAVyCl@cCZOBoBNoH\\GHe@JA@CBG?EEWBKEiDGaC[w@QkA_@eAm@aB?k@Gi@Mi@Ey@CkABG?YSeBsAuEzF_CeCeCuBsC^m@FEFQCSBwAb@}HnA]`@y@jAc@f@m@vAw@nAy@jAm@v@u@x@i@f@cAx@QFk@P_Cn@_Bd@}Ah@sDrAeBh@kAZkBb@KT}@`Ao@r@u@r@q@t@g@z@Sl@Il@Ch@Bb@FL?RGPMDIAQ?_@J{AdD]j@kAlBo@n@kA`BSf@Kd@Bt@?PANEFE@ICMMMMS?QFUVkEdH{LpUa@l@OBYAyB[CbAGtAE~BEDGBEACCCG?CBGBCFADBBB@B?HEDGBEACCCG_@OeCqAyF_D_EmCqDeDsJeHqFsEaG{EmG}EkAp@uNgMOUCMm@Hw@Bo@IkDl@yDh@iBXsAVw@Eg@FcHhAoAX{@j@kAXuAPqB`@a@JgDdAiAV_ABsAb@uBfAcEbDiBnAyAjAcA`AqBdCgAnAiG|GmAdBI^o@fDIn@a@`Bc@xAg@{@sASkCg@IoAgAA?MaBMFaAeBK{@Y}@LcAKm@Uc@Gy@PmBd@uDl@mHdAaD\\k@Jk@\\EKsCn@sLfAcCJmAI}CpMy@nDcPaEC@G?CACGs@SiGyAyBq@cDeAy@o@[QcBgCy@o@m@_@m@OgA@aL^}CNq@Cy@Mu@Ys@a@k@q@oA}BuAsBo@s@yAmAmAgAw@e@wAs@cBm@kCo@cEg@g@CwB@yBNsAJwC^}Dj@{@D}@Ae@I_ASo@Wc@We@a@mCqCWUI_@{@{@_EcDWD[@i@I{Cm@wCe@u@IqCk@uGm@e@G}@?kBF_A@mCNeCJmGLaCN}@ABWGo@Mg@UMo@CKWGWFi@p@Qc@s@a@IKGMUIQGWi@DQBID[IKIc@KM?M@a@RMFI?GAc@WCGCKDg@[BeC?{@DaA@UG_@SaA[w@SsE}@WIEGAI@QFqAPkBF}AqAGyF_@QEEIB{@ZaHlAoOgBOy@OaBs@aAm@{BmBu@aASSwDeCa@a@a@g@u@o@EGIEsAkASK_Aw@}@i@sA}@g@Y_Cu@]QWQQWOc@i@HGQMQMOgDaD{@w@cDgByBqAoDaCsF_D_@OUGUC}@GYESI_@Uq@c@s@k@gCgC_@W{@e@{Au@QEOCi@?aBHMAKCKE[WsCcDKKWOs@W}B_AMEOCm@E_@GmBa@UEQAkBGkAIMEGGk@}@Y]MMOMMEOCSCgAGQCMEKGIE?Uy@oCEWEMIKOIa@KcASIFIB_KDeLHDmEi@CGACEUyAKsACg@WLI?K?}@IBQA[GS_BoAKIIOKy@CYAe@@]g@HYHa@N[LuALuBNK?g@AgBUaCi@mB]M?C_@A_@XoHHaDHAEaF@m@AWI}JBuCFm@t@wF@a@C_AE[i@cCKw@a@_J_@oECg@k@yJK}C_@{Em@oIc@kHIgAi@gLOuBUwCMsA]}Bq@}Dk@qCoByIe@_@OKKKO_@Qk@GIGEICKAq@AmBBKAKEYYIEi@EgA?eAC}@B_AFYH[NKFODi@FO@IAGGEO]eBWu@Yk@MQOMWKqBq@GEGKK]GIKEWGgBQo@Mk@Kq@Gk@KGCEGCKKu@Sy@GYYcAS]UWQQu@q@[WYOy@]WMCCCGKi@GOo@s@_@Yc@TcB|@OFQBaBPqE|@oCn@m@Jw@AaE?i@Fm@JmAf@WFYNg@\\WTQNELc@Fa@DmBJs@@aF_@]?a@CYDyCt@]FO@wBMmAGgBd@iFnAGq@eB^cAPaFl@iC\\?l@mBXoIpBODJWAUC[OaAEg@Aa@?g@FwB@qBiLgEkCy@_GcBWGWEc@JYCEASKWWMKIOqD}DSSs@k@w@e@kG}CyAdDIEoGiDhAmCsNwHOGQAWAOyC}BNY?UGuAq@aGeDFOmGiDy@jB_HwD}@vBuN_Iw@pBk@lA]h@QKaDvHoE_COt@]bC{@tGi@jDKZKTMP_@`@sBzAwEfAsA?{Fo@?_AAGIIPiABIDG}@S|@REFCHQhAHH@F?~@zFn@rA?vEgArB{A^a@LQJUJ[h@kDz@uG\\cCNu@DUpE`CxCcHPJ\\i@j@mAv@qBtN~H|@wBtGpDv@kBxGnDGN`GdDtAp@TFX?|BONxCV@P@NFrNvHiAlCnGhDvAgDvGdDv@d@r@j@RRpD|DHNLJVVRJD@XBb@KVDVF~FbBjCx@~K`EfA^r@PlCh@x@LlA^bCz@nBp@xDk@bASn@O|HqBNd@h@JpBJvBLNA\\GxCu@XE`@B\\?`F^r@AlBK`@Eb@GDMPOVUf@]XOVGlAg@l@Kh@G`E?v@@l@KnCo@pE}@`BQPCNGbB}@b@U^Xn@r@FNJh@BFBBVLx@\\XNZVt@p@PPTVR\\XbAFXRx@Jt@BJDFFBj@Jp@Fj@Jn@LfBPVFJDFHJ\\FJFDxAd@VJVJNLLPXj@Vt@\\dBDNFFH@NAh@GNEJGZOXI~@G|@CdABfA?h@DHDXXJDJ@lBCp@@J@HBFDFHPj@N^JJNJd@^nBxIj@pCp@|D\\|BLrATvCNtBh@fLHfAb@jHl@nI^zEJ|Cn@`L^nE`@~IJv@h@bCDZB~@A`@u@vFGl@CtCH|J@VAl@D`FLAWxES~F?PBh@lB\\`Ch@fBTf@@J?tBOtAMZM`@OXIf@IA\\@d@BXJx@HNJH~AnAFR@ZCP|@HJ?H?VMBf@JrATxABDF@x@BElEtKI~JEHCHGbAR`@JNHHJDLDVx@nC?THDJFLDPBfAFRBNBLDNLLLX\\j@|@FFLDjAHjBFP@TDlB`@^Fl@DNBLD|B~@r@VVNJJrCbDZVJDJBL@`BIh@?NBPDzAt@z@d@^VfCfCr@j@p@b@^TRHXD|@FTBTF^NrF~CnD`CxBpAbDfBz@v@fD`DLNLPFPh@INb@PVVP\\P~Bt@f@XrA|@|@h@~@v@RJrAjAHDDFt@n@`@f@`@`@vDdCRRt@`AzBlB`Al@`Br@x@NfBNmAnO[`HCz@DHPDxF^pAFG|AQjBGpAAP@HDFVHrE|@v@R`AZ^RTF`AAz@EdC?ZCEf@BJBFb@VF@H?LG`@SLAL?b@JJHZHHEPCh@EFVHPLTJF`@Hb@r@q@PGh@FVJVn@BTLLf@Fn@CV|@@`COlGMdCKlCO~@AjBG|@?d@FtGl@pCj@t@HvCd@zCl@h@HZAVE~DbDz@z@RFXXv@r@a@vHK~@SlAxNpB^\\bAt@n@RxGbBnGzA|Ad@^RhBn@~FtAnLtClFxA^D|Ec@dEeAlCGfAIlBGLGlD@VFj@GDSbDdAtCx@bHhBH?DD?BfPvDpBf@vBj@`FxAxFzAxGhBFLxAfAjG|GVf@XQj@l@RJVBP?LEPMBRBJrEzByAtDORGDI@xA`@nAXZD^BpACRDPBhDMv@EFVDXDnAiA`@xBnJxC~F`AjC~AjATDXt@z@dF~UeA\\CzEA|BCHGBSb@Cj@Vf@TbANXjDnNy@nBOtAfF~@tDj@|@rAy@`K~Zn@|B`HlTZv@DFHBtCn@vEr@h@LJ@`Ep@xLzBdDr@`Dh@hIdBfI~AjI|A|NzCjIzB~KvDrG~BLNPNLH|H~CdIxCfBgFxA^^T|CtAfC|@|L|EHY~G`CfLxEn@gB`Bt@lAf@tEdAVBH@zAEtAGlCWzCO`BBxB@lDFnANRExDKp@?HDnBBpACvBG~EEd@?\\APCFCVUXOBGPM^Er@Gv@Sj@WlBk@d@IP@`COv@Ml@QlBs@pAk@XSRKNQx@]d@Mj@Gd@A^@FDX?\\@n@AzAInCQlBUlA[rDgArBk@p@SPKLEfAc@~CoA\\Ox@Oz@Ep@?|AFvC@rAFd@EnCGYyEAS^Dj@@@PJ~Dd@H`@APAZEbBKn@Kl@m@JNLDvDK~BCpCPx@h@b@^h@|@l@\\TNTTTXPDLIB?FB\\NPJBFl@V@?DCHGPDD?\\ApABT?NAVKPKCELIBD~BvD^j@l@`AtBtClHlIDADBBB@FADABdClCl@lACbJDXFVxC_Af@GjBCfGLb@Bt@DVHxAv@dAr@bBrAf@ZZBx@RnA`@Jv@b@~BbExArC~@lDjANDjBX`BFlAF|BZ`AJnCB`@Cx@f@bA?fBXfA`@x@n@PP~AdAn@r@bArAK`AXr@ZL^\\NR?fADh@?~@Ch@Gb@SdA~DaA~BMTnB@pDChB`IP",
        team_member_id: 2,
        team_member_name: "second driver",
        total_distance_meters: 87568,
        total_duration_seconds: 89760,
      },
      {
        stops: [
          {
            job_id: 2,
            stop_type: "job",
            arrival_time: "2025-12-02T13:56:07",
            latitude: 37.7749,
            longitude: -122.4194,
          },
          {
            job_id: 6,
            stop_type: "job",
            arrival_time: "2025-12-02T14:46:02",
            latitude: 37.7849,
            longitude: -122.4094,
          },
          {
            job_id: 5,
            stop_type: "job",
            arrival_time: "2025-12-02T18:48:45",
            latitude: 37.7649,
            longitude: -122.4294,
          },
        ],
        vehicle_id: 3,
        route_polyline:
          "kzfkCawnyLyGOF[PMnAWFC@IOo@i@kBYqACOAU?O@_@XEhGeH_DiC{C_Fu@{@Uu@rAy@fAi@f@YzAu@fA]~@a@PCYm@Tu@Bo@Uk@bAsBz@{DL{@\\uCHcAkAQf@}CRq@SSa@c@OUOIOi@KcBI_@Qo@IKEGSKKADe@CMw@_AIOAMAMBM@EV_@BMBOKSYs@IgAGyCBo@I_C@UCyBRsANyAiE[sBW_BIu@uJi@FeAyDaBl@Ou@kAeEI]CUC}AM{DAeGImCB@b@SVG}AaJ}DsTkFuXs@}CmGeRkBuEm@KYAUi@Ue@dKuGbYqQfFeDVj@bFrLl@nAfCtD`BtBxApBnBrCxAlBhAExCUtCuAzBs@nB?hBW|@IlAZjAf@bAdAvBnAvAf@~@^dBoHBS`DD\\ARL?G@CDC@U`ELLcEBcBF{AL@fAHnAHp@ABsAHiAhAaC|CwEjByGbBgOAcC[mF@_Hb@uDd@qC`DsMqBm@`BkF`BqHx@m@pCaCp@yCFmD@qE]cHMaFkA_LaAgC_B}CcB{EV_DNsEr@_FNkBFkDAuCEmAYeCaAgCGaB[}Bk@oC[uAU_DB[GmCF{C?uCc@{DKmCMkCW_Do@qB@Y~A_AOu@vFaCm@qB@{Au@Xs@RmCmIGIyAwDg@b@g@w@IODm@FG@UfC{QoBBUMWuBEMKEqEVW?OGM_@i@}E_AeGa@H[FEkAC_@Mw@QgCGM]YyBqBaBaBa@e@g@{@NU@UEOe@y@l@_@s@sCK@}B}K_@wAsC|@c@uAEAGI]}Ao@gCUo@]Ts@kBkAaDgAiCYm@AG@GN]f@_ARa@dCgE^i@Z_@vCeHjA}Cp@cBhBwCj@w@~AoFjAiENk@XcBrCh@d@LhATQjAPkAiAUe@MsCi@YbBOj@kAhE_BnFeAa@mDeBkFq@oASIRSd@MTSXgB~BwAtBmB`CiAnA}@t@yBbBoAjAw@h@uBAgOSS@i@?_@IeMYgDMsXs@eAAKG[Bm@Bi@CAFW|DQfAI\\@VuAfJiBbKi@zDO`BStCg@nGExAB`FYjG@tA@zFKfFCbCSRoATc@JoHxCYRM^C^?dBClAEVSVYFe@@{C?wBFUrEIlBe@Ck@BsABq@YCRoAzEqBjEa@Ar@vC@LuAKeFaAg@hC}CDQdBGx@Kj@o@jBgAjCUDe@EmASaB[wCk@w@GU@a@CwCK}AFqAF}@\\oAj@oAb@gCx@A}@e@DSHs@DkAFMoCoHPGB]BCDA@G?ECg@@KCcD?_DMkB?iBIsASeA[sBu@s@e@{Ac@aAKcAAsA\\QJ?FCBA@E??BLfBAj@C\\YFoC\\g@d@MOmA^DlAeBO}Ck@YhCq@xAaAfBqBUQxAUdASL?XDFa@~AUz@EbAI`@[tAN?_@f@gA|@g@TIQ_AB{FSeDD_@fDWbCCz@@x@DhDEd@Ot@El@u@bY?NExCAzBH\\R`@DXPr@Fn@EPVbGDbFj@nEsAVyCl@cCZOBoBNoH\\GHe@JA@CBG?EEWBKEiDGaC[w@QkA_@eAm@aB?k@Gi@Mi@Ey@CkABG?YSeBsAuEzF_CeCeCuBsC^m@FEFQCSBwAb@}HnA]`@y@jAc@f@m@vAw@nAy@jAm@v@u@x@i@f@cAx@QFk@P_Cn@_Bd@}Ah@sDrAeBh@kAZkBb@KT}@`Ao@r@u@r@q@t@g@z@Sl@Il@Ch@Bb@FL?RGPMDIAQ?_@J{AdD]j@kAlBo@n@kA`BSf@Kd@Bt@?PANEFE@ICMMMMS?QFUVkEdH{LpUa@l@OBYAyB[CbAGtAE~BEDGBEACCCG?CBGBCFADBBB@B?HEDGBEACCCG_@OeCqAyF_D_EmCqDeDsJeHqFsEaG{EmG}EkAp@uNgMOUCMm@Hw@Bo@IkDl@yDh@iBXsAVw@Eg@FcHhAoAX{@j@kAXuAPqB`@a@JgDdAiAV_ABsAb@uBfAcEbDiBnAyAjAcA`AqBdCgAnAiG|GmAdBI^o@fDIn@a@`Bc@xAg@{@sASkCg@IoAgAA?MaBMFaAeBK{@Y}@LcAKm@Uc@Gy@PmBd@uDl@mHdAaD\\k@Jk@\\EKsCn@sLfAcCJmAI}CpMy@nDcPaEC@G?CACGs@SiGyAyBq@cDeAy@o@[QcBgCy@o@m@_@m@OgA@aL^}CNq@Cy@Mu@Ys@a@k@q@oA}BuAsBo@s@yAmAmAgAw@e@wAs@cBm@kCo@cEg@g@CwB@yBNsAJwC^}Dj@{@D}@Ae@I_ASo@Wc@We@a@mCqCWUI_@{@{@_EcDWD[@i@I{Cm@wCe@u@IqCk@uGm@e@G}@?kBF_A@mCNeCJmGLaCN}@ABWGo@Mg@UMo@CKWGWFi@p@Qc@s@a@IKGMUIQGWi@DQBID[IKIc@KM?M@a@RMFI?GAc@WCGCKDg@[BeC?{@DaA@UG_@SaA[w@SsE}@WIEGAI@QFqAPkBF}AqAGyF_@QEEIB{@ZaHlAoOgBOy@OaBs@aAm@{BmBu@aASSwDeCa@a@a@g@u@o@EGIEsAkASK_Aw@}@i@sA}@g@Y_Cu@]QWQQWOc@i@HGQMQMOgDaD{@w@cDgByBqAoDaCsF_D_@OUGUC}@GYESI_@Uq@c@s@k@gCgC_@W{@e@{Au@QEOCi@?aBHMAKCKE[WsCcDKKWOs@W}B_AMEOCm@E_@GmBa@UEQAkBGkAIMEGGk@}@Y]MMOMMEOCSCgAGQCMEKGIE?Uy@oCEWEMIKOIa@KcASIFIB_KDeLHDmEi@CGACEUyAKsACg@WLI?K?}@IBQA[GS_BoAKIIOKy@CYAe@@]g@HYHa@N[LuALuBNK?g@AgBUaCi@mB]M?C_@A_@XoHHaDHAEaF@m@AWI}JBuCFm@t@wF@a@C_AE[i@cCKw@a@_J_@oECg@k@yJK}C_@{Em@oIc@kHIgAi@gLOuBUwCMsA]}Bq@}Dk@qCoByIe@_@OKKKO_@Qk@GIGEICKAq@AmBBKAKEYYIEi@EgA?eAC}@B_AFYH[NKFODi@FO@IAGGEO]eBWu@Yk@MQOMWKqBq@GEGKK]GIKEWGgBQo@Mk@Kq@Gk@KGCEGCKKu@Sy@GYYcAS]UWQQu@q@[WYOy@]WMCCCGKi@GOo@s@_@Yc@TcB|@OFQBaBPqE|@oCn@m@Jw@AaE?i@Fm@JmAf@WFYNg@\\WTQNELc@Fa@DmBJs@@aF_@]?a@CYDyCt@]FO@wBMmAGgBd@iFnAGq@eB^cAPaFl@iC\\?l@mBXoIpBODJWAUC[OaAEg@Aa@?g@FwB@qBiLgEkCy@_GcBWGWEc@JYCEASKWWMKIOqD}DSSs@k@w@e@kG}CyAdDIEoGiDhAmCsNwHOGQAWAOyC}BNY?UGuAq@aGeDFOmGiDy@jB_HwD}@vBuN_Iw@pBk@lA]h@QKaDvHoE_COt@]bC{@tGi@jDKZKTMP_@`@sBzAwEfAsA?{Fo@?_AAGIIPiABIDG}@S|@REFCHQhAHH@F?~@zFn@rA?vEgArB{A^a@LQJUJ[h@kDz@uG\\cCNu@DUpE`CxCcHPJ\\i@j@mAv@qBtN~H|@wBtGpDv@kBxGnDGN`GdDtAp@TFX?|BONxCV@P@NFrNvHiAlCnGhDvAgDvGdDv@d@r@j@RRpD|DHNLJVVRJD@XBb@KVDVF~FbBjCx@~K`EfA^r@PlCh@x@LlA^bCz@nBp@xDk@bASn@O|HqBNd@h@JpBJvBLNA\\GxCu@XE`@B\\?`F^r@AlBK`@Eb@GDMPOVUf@]XOVGlAg@l@Kh@G`E?v@@l@KnCo@pE}@`BQPCNGbB}@b@U^Xn@r@FNJh@BFBBVLx@\\XNZVt@p@PPTVR\\XbAFXRx@Jt@BJDFFBj@Jp@Fj@Jn@LfBPVFJDFHJ\\FJFDxAd@VJVJNLLPXj@Vt@\\dBDNFFH@NAh@GNEJGZOXI~@G|@CdABfA?h@DHDXXJDJ@lBCp@@J@HBFDFHPj@N^JJNJd@^nBxIj@pCp@|D\\|BLrATvCNtBh@fLHfAb@jHl@nI^zEJ|Cn@`L^nE`@~IJv@h@bCDZB~@A`@u@vFGl@CtCH|J@VAl@D`FLAWxES~F?PBh@lB\\`Ch@fBTf@@J?tBOtAMZM`@OXIf@IA\\@d@BXJx@HNJH~AnAFR@ZCP|@HJ?H?VMBf@JrATxABDF@x@BElEtKI~JEHCHGbAR`@JNHHJDLDVx@nC?THDJFLDPBfAFRBNBLDNLLLX\\j@|@FFLDjAHjBFP@TDlB`@^Fl@DNBLD|B~@r@VVNJJrCbDZVJDJBL@`BIh@?NBPDzAt@z@d@^VfCfCr@j@p@b@^TRHXD|@FTBTF^NrF~CnD`CxBpAbDfBz@v@fD`DLNLPFPh@INb@PVVP\\P~Bt@f@XrA|@|@h@~@v@RJrAjAHDDFt@n@`@f@`@`@vDdCRRt@`AzBlB`Al@`Br@x@NfBNmAnO[`HCz@DHPDxF^pAFG|AQjBGpAAP@HDFVHrE|@v@R`AZ^RTF`AAz@EdC?ZCEf@BJBFb@VF@H?LG`@SLAL?b@JJHZHHEPCh@EFVHPLTJF`@Hb@r@q@PGh@FVJVn@BTLLf@Fn@CV|@@`COlGMdCKlCO~@AjBG|@?d@FtGl@pCj@t@HvCd@zCl@h@HZAVE~DbDz@z@RFXXv@r@a@vHK~@SlAxNpB^\\bAt@n@RxGbBnGzA|Ad@^RhBn@~FtAnLtClFxA^D|Ec@dEeAlCGfAIlBGLGlD@VFj@GDSbDdAtCx@bHhBH?DD?BfPvDpBf@vBj@`FxAxFzAxGhBFLxAfAjG|GVf@XQj@l@RJVBP?LEPMBRBJrEzByAtDORGDI@xA`@nAXZD^BpACRDPBhDMv@EFVDXDnAiA`@xBnJxC~F`AjC~AjATDXt@z@dF~UeA\\CzEA|BCHGBSb@Cj@Vf@TbANXjDnNy@nBOtAfF~@tDj@|@rAy@`K~Zn@|B`HlTZv@DFHBtCn@vEr@h@LJ@`Ep@xLzBdDr@`Dh@hIdBfI~AjI|A|NzCjIzB~KvDrG~BLNPNLH|H~CdIxCfBgFxA^^T|CtAfC|@|L|EHY~G`CfLxEn@gB`Bt@lAf@tEdAVBH@zAEtAGlCWzCO`BBxB@lDFnANRExDKp@?HDnBBpACvBG~EEd@?\\APCFCVUXOBGPM^Er@Gv@Sj@WlBk@d@IP@`COv@Ml@QlBs@pAk@XSRKNQx@]d@Mj@Gd@A^@FDX?\\@n@AzAInCQlBUlA[rDgArBk@p@SPKLEfAc@~CoA\\Ox@Oz@Ep@?|AFvC@rAFd@EnCGYyEAS^Dj@@@PJ~Dd@H`@APAZEbBKn@Kl@m@JNLDvDK~BCpCPx@h@b@^h@|@l@\\TNTTTXPDLIB?FB\\NPJBFl@V@?DCHGPDD?\\ApABT?NAVKPKCELIBD~BvD^j@l@`AtBtClHlIDADBBB@FADABdClCl@lACbJDXFVxC_Af@GjBCfGLb@Bt@DVHxAv@dAr@bBrAf@ZZBx@RnA`@Jv@b@~BbExArC~@lDjANDjBX`BFlAF|BZ`AJnCB`@Cx@f@bA?fBXfA`@x@n@PP~AdAn@r@bArAK`AXr@ZL^\\NR?fADh@?~@Ch@Gb@SdA~DaA~BMTnB@pDChB`IP",
        team_member_id: 2,
        team_member_name: "second driver",
        total_distance_meters: 87568,
        total_duration_seconds: 62260,
      },
      {
        stops: [
          {
            job_id: 2,
            stop_type: "job",
            arrival_time: "2025-12-02T13:56:07",
            latitude: 37.7749,
            longitude: -122.4194,
          },
          {
            job_id: 6,
            stop_type: "job",
            arrival_time: "2025-12-02T14:46:02",
            latitude: 37.7849,
            longitude: -122.4094,
          },
          {
            job_id: 5,
            stop_type: "job",
            arrival_time: "2025-12-02T18:48:45",
            latitude: 37.7649,
            longitude: -122.4294,
          },
        ],
        vehicle_id: 3,
        route_polyline:
          "kzfkCawnyLyGOF[PMnAWFC@IOo@i@kBYqACOAU?O@_@XEhGeH_DiC{C_Fu@{@Uu@rAy@fAi@f@YzAu@fA]~@a@PCYm@Tu@Bo@Uk@bAsBz@{DL{@\\uCHcAkAQf@}CRq@SSa@c@OUOIOi@KcBI_@Qo@IKEGSKKADe@CMw@_AIOAMAMBM@EV_@BMBOKSYs@IgAGyCBo@I_C@UCyBRsANyAiE[sBW_BIu@uJi@FeAyDaBl@Ou@kAeEI]CUC}AM{DAeGImCB@b@SVG}AaJ}DsTkFuXs@}CmGeRkBuEm@KYAUi@Ue@dKuGbYqQfFeDVj@bFrLl@nAfCtD`BtBxApBnBrCxAlBhAExCUtCuAzBs@nB?hBW|@IlAZjAf@bAdAvBnAvAf@~@^dBoHBS`DD\\ARL?G@CDC@U`ELLcEBcBF{AL@fAHnAHp@ABsAHiAhAaC|CwEjByGbBgOAcC[mF@_Hb@uDd@qC`DsMqBm@`BkF`BqHx@m@pCaCp@yCFmD@qE]cHMaFkA_LaAgC_B}CcB{EV_DNsEr@_FNkBFkDAuCEmAYeCaAgCGaB[}Bk@oC[uAU_DB[GmCF{C?uCc@{DKmCMkCW_Do@qB@Y~A_AOu@vFaCm@qB@{Au@Xs@RmCmIGIyAwDg@b@g@w@IODm@FG@UfC{QoBBUMWuBEMKEqEVW?OGM_@i@}E_AeGa@H[FEkAC_@Mw@QgCGM]YyBqBaBaBa@e@g@{@NU@UEOe@y@l@_@s@sCK@}B}K_@wAsC|@c@uAEAGI]}Ao@gCUo@]Ts@kBkAaDgAiCYm@AG@GN]f@_ARa@dCgE^i@Z_@vCeHjA}Cp@cBhBwCj@w@~AoFjAiENk@XcBrCh@d@LhATQjAPkAiAUe@MsCi@YbBOj@kAhE_BnFeAa@mDeBkFq@oASIRSd@MTSXgB~BwAtBmB`CiAnA}@t@yBbBoAjAw@h@uBAgOSS@i@?_@IeMYgDMsXs@eAAKG[Bm@Bi@CAFW|DQfAI\\@VuAfJiBbKi@zDO`BStCg@nGExAB`FYjG@tA@zFKfFCbCSRoATc@JoHxCYRM^C^?dBClAEVSVYFe@@{C?wBFUrEIlBe@Ck@BsABq@YCRoAzEqBjEa@Ar@vC@LuAKeFaAg@hC}CDQdBGx@Kj@o@jBgAjCUDe@EmASaB[wCk@w@GU@a@CwCK}AFqAF}@\\oAj@oAb@gCx@A}@e@DSHs@DkAFMoCoHPGB]BCDA@G?ECg@@KCcD?_DMkB?iBIsASeA[sBu@s@e@{Ac@aAKcAAsA\\QJ?FCBA@E??BLfBAj@C\\YFoC\\g@d@MOmA^DlAeBO}Ck@YhCq@xAaAfBqBUQxAUdASL?XDFa@~AUz@EbAI`@[tAN?_@f@gA|@g@TIQ_AB{FSeDD_@fDWbCCz@@x@DhDEd@Ot@El@u@bY?NExCAzBH\\R`@DXPr@Fn@EPVbGDbFj@nEsAVyCl@cCZOBoBNoH\\GHe@JA@CBG?EEWBKEiDGaC[w@QkA_@eAm@aB?k@Gi@Mi@Ey@CkABG?YSeBsAuEzF_CeCeCuBsC^m@FEFQCSBwAb@}HnA]`@y@jAc@f@m@vAw@nAy@jAm@v@u@x@i@f@cAx@QFk@P_Cn@_Bd@}Ah@sDrAeBh@kAZkBb@KT}@`Ao@r@u@r@q@t@g@z@Sl@Il@Ch@Bb@FL?RGPMDIAQ?_@J{AdD]j@kAlBo@n@kA`BSf@Kd@Bt@?PANEFE@ICMMMMS?QFUVkEdH{LpUa@l@OBYAyB[CbAGtAE~BEDGBEACCCG?CBGBCFADBBB@B?HEDGBEACCCG_@OeCqAyF_D_EmCqDeDsJeHqFsEaG{EmG}EkAp@uNgMOUCMm@Hw@Bo@IkDl@yDh@iBXsAVw@Eg@FcHhAoAX{@j@kAXuAPqB`@a@JgDdAiAV_ABsAb@uBfAcEbDiBnAyAjAcA`AqBdCgAnAiG|GmAdBI^o@fDIn@a@`Bc@xAg@{@sASkCg@IoAgAA?MaBMFaAeBK{@Y}@LcAKm@Uc@Gy@PmBd@uDl@mHdAaD\\k@Jk@\\EKsCn@sLfAcCJmAI}CpMy@nDcPaEC@G?CACGs@SiGyAyBq@cDeAy@o@[QcBgCy@o@m@_@m@OgA@aL^}CNq@Cy@Mu@Ys@a@k@q@oA}BuAsBo@s@yAmAmAgAw@e@wAs@cBm@kCo@cEg@g@CwB@yBNsAJwC^}Dj@{@D}@Ae@I_ASo@Wc@We@a@mCqCWUI_@{@{@_EcDWD[@i@I{Cm@wCe@u@IqCk@uGm@e@G}@?kBF_A@mCNeCJmGLaCN}@ABWGo@Mg@UMo@CKWGWFi@p@Qc@s@a@IKGMUIQGWi@DQBID[IKIc@KM?M@a@RMFI?GAc@WCGCKDg@[BeC?{@DaA@UG_@SaA[w@SsE}@WIEGAI@QFqAPkBF}AqAGyF_@QEEIB{@ZaHlAoOgBOy@OaBs@aAm@{BmBu@aASSwDeCa@a@a@g@u@o@EGIEsAkASK_Aw@}@i@sA}@g@Y_Cu@]QWQQWOc@i@HGQMQMOgDaD{@w@cDgByBqAoDaCsF_D_@OUGUC}@GYESI_@Uq@c@s@k@gCgC_@W{@e@{Au@QEOCi@?aBHMAKCKE[WsCcDKKWOs@W}B_AMEOCm@E_@GmBa@UEQAkBGkAIMEGGk@}@Y]MMOMMEOCSCgAGQCMEKGIE?Uy@oCEWEMIKOIa@KcASIFIB_KDeLHDmEi@CGACEUyAKsACg@WLI?K?}@IBQA[GS_BoAKIIOKy@CYAe@@]g@HYHa@N[LuALuBNK?g@AgBUaCi@mB]M?C_@A_@XoHHaDHAEaF@m@AWI}JBuCFm@t@wF@a@C_AE[i@cCKw@a@_J_@oECg@k@yJK}C_@{Em@oIc@kHIgAi@gLOuBUwCMsA]}Bq@}Dk@qCoByIe@_@OKKKO_@Qk@GIGEICKAq@AmBBKAKEYYIEi@EgA?eAC}@B_AFYH[NKFODi@FO@IAGGEO]eBWu@Yk@MQOMWKqBq@GEGKK]GIKEWGgBQo@Mk@Kq@Gk@KGCEGCKKu@Sy@GYYcAS]UWQQu@q@[WYOy@]WMCCCGKi@GOo@s@_@Yc@TcB|@OFQBaBPqE|@oCn@m@Jw@AaE?i@Fm@JmAf@WFYNg@\\WTQNELc@Fa@DmBJs@@aF_@]?a@CYDyCt@]FO@wBMmAGgBd@iFnAGq@eB^cAPaFl@iC\\?l@mBXoIpBODJWAUC[OaAEg@Aa@?g@FwB@qBiLgEkCy@_GcBWGWEc@JYCEASKWWMKIOqD}DSSs@k@w@e@kG}CyAdDIEoGiDhAmCsNwHOGQAWAOyC}BNY?UGuAq@aGeDFOmGiDy@jB_HwD}@vBuN_Iw@pBk@lA]h@QKaDvHoE_COt@]bC{@tGi@jDKZKTMP_@`@sBzAwEfAsA?{Fo@?_AAGIIPiABIDG}@S|@REFCHQhAHH@F?~@zFn@rA?vEgArB{A^a@LQJUJ[h@kDz@uG\\cCNu@DUpE`CxCcHPJ\\i@j@mAv@qBtN~H|@wBtGpDv@kBxGnDGN`GdDtAp@TFX?|BONxCV@P@NFrNvHiAlCnGhDvAgDvGdDv@d@r@j@RRpD|DHNLJVVRJD@XBb@KVDVF~FbBjCx@~K`EfA^r@PlCh@x@LlA^bCz@nBp@xDk@bASn@O|HqBNd@h@JpBJvBLNA\\GxCu@XE`@B\\?`F^r@AlBK`@Eb@GDMPOVUf@]XOVGlAg@l@Kh@G`E?v@@l@KnCo@pE}@`BQPCNGbB}@b@U^Xn@r@FNJh@BFBBVLx@\\XNZVt@p@PPTVR\\XbAFXRx@Jt@BJDFFBj@Jp@Fj@Jn@LfBPVFJDFHJ\\FJFDxAd@VJVJNLLPXj@Vt@\\dBDNFFH@NAh@GNEJGZOXI~@G|@CdABfA?h@DHDXXJDJ@lBCp@@J@HBFDFHPj@N^JJNJd@^nBxIj@pCp@|D\\|BLrATvCNtBh@fLHfAb@jHl@nI^zEJ|Cn@`L^nE`@~IJv@h@bCDZB~@A`@u@vFGl@CtCH|J@VAl@D`FLAWxES~F?PBh@lB\\`Ch@fBTf@@J?tBOtAMZM`@OXIf@IA\\@d@BXJx@HNJH~AnAFR@ZCP|@HJ?H?VMBf@JrATxABDF@x@BElEtKI~JEHCHGbAR`@JNHHJDLDVx@nC?THDJFLDPBfAFRBNBLDNLLLX\\j@|@FFLDjAHjBFP@TDlB`@^Fl@DNBLD|B~@r@VVNJJrCbDZVJDJBL@`BIh@?NBPDzAt@z@d@^VfCfCr@j@p@b@^TRHXD|@FTBTF^NrF~CnD`CxBpAbDfBz@v@fD`DLNLPFPh@INb@PVVP\\P~Bt@f@XrA|@|@h@~@v@RJrAjAHDDFt@n@`@f@`@`@vDdCRRt@`AzBlB`Al@`Br@x@NfBNmAnO[`HCz@DHPDxF^pAFG|AQjBGpAAP@HDFVHrE|@v@R`AZ^RTF`AAz@EdC?ZCEf@BJBFb@VF@H?LG`@SLAL?b@JJHZHHEPCh@EFVHPLTJF`@Hb@r@q@PGh@FVJVn@BTLLf@Fn@CV|@@`COlGMdCKlCO~@AjBG|@?d@FtGl@pCj@t@HvCd@zCl@h@HZAVE~DbDz@z@RFXXv@r@a@vHK~@SlAxNpB^\\bAt@n@RxGbBnGzA|Ad@^RhBn@~FtAnLtClFxA^D|Ec@dEeAlCGfAIlBGLGlD@VFj@GDSbDdAtCx@bHhBH?DD?BfPvDpBf@vBj@`FxAxFzAxGhBFLxAfAjG|GVf@XQj@l@RJVBP?LEPMBRBJrEzByAtDORGDI@xA`@nAXZD^BpACRDPBhDMv@EFVDXDnAiA`@xBnJxC~F`AjC~AjATDXt@z@dF~UeA\\CzEA|BCHGBSb@Cj@Vf@TbANXjDnNy@nBOtAfF~@tDj@|@rAy@`K~Zn@|B`HlTZv@DFHBtCn@vEr@h@LJ@`Ep@xLzBdDr@`Dh@hIdBfI~AjI|A|NzCjIzB~KvDrG~BLNPNLH|H~CdIxCfBgFxA^^T|CtAfC|@|L|EHY~G`CfLxEn@gB`Bt@lAf@tEdAVBH@zAEtAGlCWzCO`BBxB@lDFnANRExDKp@?HDnBBpACvBG~EEd@?\\APCFCVUXOBGPM^Er@Gv@Sj@WlBk@d@IP@`COv@Ml@QlBs@pAk@XSRKNQx@]d@Mj@Gd@A^@FDX?\\@n@AzAInCQlBUlA[rDgArBk@p@SPKLEfAc@~CoA\\Ox@Oz@Ep@?|AFvC@rAFd@EnCGYyEAS^Dj@@@PJ~Dd@H`@APAZEbBKn@Kl@m@JNLDvDK~BCpCPx@h@b@^h@|@l@\\TNTTTXPDLIB?FB\\NPJBFl@V@?DCHGPDD?\\ApABT?NAVKPKCELIBD~BvD^j@l@`AtBtClHlIDADBBB@FADABdClCl@lACbJDXFVxC_Af@GjBCfGLb@Bt@DVHxAv@dAr@bBrAf@ZZBx@RnA`@Jv@b@~BbExArC~@lDjANDjBX`BFlAF|BZ`AJnCB`@Cx@f@bA?fBXfA`@x@n@PP~AdAn@r@bArAK`AXr@ZL^\\NR?fADh@?~@Ch@Gb@SdA~DaA~BMTnB@pDChB`IP",
        team_member_id: 2,
        team_member_name: "second driver",
        total_distance_meters: 87568,
        total_duration_seconds: 62260,
      },
      {
        stops: [
          {
            job_id: 2,
            stop_type: "job",
            arrival_time: "2025-12-02T13:56:07",
            latitude: 37.7749,
            longitude: -122.4194,
          },
          {
            job_id: 6,
            stop_type: "job",
            arrival_time: "2025-12-02T14:46:02",
            latitude: 37.7849,
            longitude: -122.4094,
          },
          {
            job_id: 5,
            stop_type: "job",
            arrival_time: "2025-12-02T18:48:45",
            latitude: 37.7649,
            longitude: -122.4294,
          },
        ],
        vehicle_id: 3,
        route_polyline:
          "kzfkCawnyLyGOF[PMnAWFC@IOo@i@kBYqACOAU?O@_@XEhGeH_DiC{C_Fu@{@Uu@rAy@fAi@f@YzAu@fA]~@a@PCYm@Tu@Bo@Uk@bAsBz@{DL{@\\uCHcAkAQf@}CRq@SSa@c@OUOIOi@KcBI_@Qo@IKEGSKKADe@CMw@_AIOAMAMBM@EV_@BMBOKSYs@IgAGyCBo@I_C@UCyBRsANyAiE[sBW_BIu@uJi@FeAyDaBl@Ou@kAeEI]CUC}AM{DAeGImCB@b@SVG}AaJ}DsTkFuXs@}CmGeRkBuEm@KYAUi@Ue@dKuGbYqQfFeDVj@bFrLl@nAfCtD`BtBxApBnBrCxAlBhAExCUtCuAzBs@nB?hBW|@IlAZjAf@bAdAvBnAvAf@~@^dBoHBS`DD\\ARL?G@CDC@U`ELLcEBcBF{AL@fAHnAHp@ABsAHiAhAaC|CwEjByGbBgOAcC[mF@_Hb@uDd@qC`DsMqBm@`BkF`BqHx@m@pCaCp@yCFmD@qE]cHMaFkA_LaAgC_B}CcB{EV_DNsEr@_FNkBFkDAuCEmAYeCaAgCGaB[}Bk@oC[uAU_DB[GmCF{C?uCc@{DKmCMkCW_Do@qB@Y~A_AOu@vFaCm@qB@{Au@Xs@RmCmIGIyAwDg@b@g@w@IODm@FG@UfC{QoBBUMWuBEMKEqEVW?OGM_@i@}E_AeGa@H[FEkAC_@Mw@QgCGM]YyBqBaBaBa@e@g@{@NU@UEOe@y@l@_@s@sCK@}B}K_@wAsC|@c@uAEAGI]}Ao@gCUo@]Ts@kBkAaDgAiCYm@AG@GN]f@_ARa@dCgE^i@Z_@vCeHjA}Cp@cBhBwCj@w@~AoFjAiENk@XcBrCh@d@LhATQjAPkAiAUe@MsCi@YbBOj@kAhE_BnFeAa@mDeBkFq@oASIRSd@MTSXgB~BwAtBmB`CiAnA}@t@yBbBoAjAw@h@uBAgOSS@i@?_@IeMYgDMsXs@eAAKG[Bm@Bi@CAFW|DQfAI\\@VuAfJiBbKi@zDO`BStCg@nGExAB`FYjG@tA@zFKfFCbCSRoATc@JoHxCYRM^C^?dBClAEVSVYFe@@{C?wBFUrEIlBe@Ck@BsABq@YCRoAzEqBjEa@Ar@vC@LuAKeFaAg@hC}CDQdBGx@Kj@o@jBgAjCUDe@EmASaB[wCk@w@GU@a@CwCK}AFqAF}@\\oAj@oAb@gCx@A}@e@DSHs@DkAFMoCoHPGB]BCDA@G?ECg@@KCcD?_DMkB?iBIsASeA[sBu@s@e@{Ac@aAKcAAsA\\QJ?FCBA@E??BLfBAj@C\\YFoC\\g@d@MOmA^DlAeBO}Ck@YhCq@xAaAfBqBUQxAUdASL?XDFa@~AUz@EbAI`@[tAN?_@f@gA|@g@TIQ_AB{FSeDD_@fDWbCCz@@x@DhDEd@Ot@El@u@bY?NExCAzBH\\R`@DXPr@Fn@EPVbGDbFj@nEsAVyCl@cCZOBoBNoH\\GHe@JA@CBG?EEWBKEiDGaC[w@QkA_@eAm@aB?k@Gi@Mi@Ey@CkABG?YSeBsAuEzF_CeCeCuBsC^m@FEFQCSBwAb@}HnA]`@y@jAc@f@m@vAw@nAy@jAm@v@u@x@i@f@cAx@QFk@P_Cn@_Bd@}Ah@sDrAeBh@kAZkBb@KT}@`Ao@r@u@r@q@t@g@z@Sl@Il@Ch@Bb@FL?RGPMDIAQ?_@J{AdD]j@kAlBo@n@kA`BSf@Kd@Bt@?PANEFE@ICMMMMS?QFUVkEdH{LpUa@l@OBYAyB[CbAGtAE~BEDGBEACCCG?CBGBCFADBBB@B?HEDGBEACCCG_@OeCqAyF_D_EmCqDeDsJeHqFsEaG{EmG}EkAp@uNgMOUCMm@Hw@Bo@IkDl@yDh@iBXsAVw@Eg@FcHhAoAX{@j@kAXuAPqB`@a@JgDdAiAV_ABsAb@uBfAcEbDiBnAyAjAcA`AqBdCgAnAiG|GmAdBI^o@fDIn@a@`Bc@xAg@{@sASkCg@IoAgAA?MaBMFaAeBK{@Y}@LcAKm@Uc@Gy@PmBd@uDl@mHdAaD\\k@Jk@\\EKsCn@sLfAcCJmAI}CpMy@nDcPaEC@G?CACGs@SiGyAyBq@cDeAy@o@[QcBgCy@o@m@_@m@OgA@aL^}CNq@Cy@Mu@Ys@a@k@q@oA}BuAsBo@s@yAmAmAgAw@e@wAs@cBm@kCo@cEg@g@CwB@yBNsAJwC^}Dj@{@D}@Ae@I_ASo@Wc@We@a@mCqCWUI_@{@{@_EcDWD[@i@I{Cm@wCe@u@IqCk@uGm@e@G}@?kBF_A@mCNeCJmGLaCN}@ABWGo@Mg@UMo@CKWGWFi@p@Qc@s@a@IKGMUIQGWi@DQBID[IKIc@KM?M@a@RMFI?GAc@WCGCKDg@[BeC?{@DaA@UG_@SaA[w@SsE}@WIEGAI@QFqAPkBF}AqAGyF_@QEEIB{@ZaHlAoOgBOy@OaBs@aAm@{BmBu@aASSwDeCa@a@a@g@u@o@EGIEsAkASK_Aw@}@i@sA}@g@Y_Cu@]QWQQWOc@i@HGQMQMOgDaD{@w@cDgByBqAoDaCsF_D_@OUGUC}@GYESI_@Uq@c@s@k@gCgC_@W{@e@{Au@QEOCi@?aBHMAKCKE[WsCcDKKWOs@W}B_AMEOCm@E_@GmBa@UEQAkBGkAIMEGGk@}@Y]MMOMMEOCSCgAGQCMEKGIE?Uy@oCEWEMIKOIa@KcASIFIB_KDeLHDmEi@CGACEUyAKsACg@WLI?K?}@IBQA[GS_BoAKIIOKy@CYAe@@]g@HYHa@N[LuALuBNK?g@AgBUaCi@mB]M?C_@A_@XoHHaDHAEaF@m@AWI}JBuCFm@t@wF@a@C_AE[i@cCKw@a@_J_@oECg@k@yJK}C_@{Em@oIc@kHIgAi@gLOuBUwCMsA]}Bq@}Dk@qCoByIe@_@OKKKO_@Qk@GIGEICKAq@AmBBKAKEYYIEi@EgA?eAC}@B_AFYH[NKFODi@FO@IAGGEO]eBWu@Yk@MQOMWKqBq@GEGKK]GIKEWGgBQo@Mk@Kq@Gk@KGCEGCKKu@Sy@GYYcAS]UWQQu@q@[WYOy@]WMCCCGKi@GOo@s@_@Yc@TcB|@OFQBaBPqE|@oCn@m@Jw@AaE?i@Fm@JmAf@WFYNg@\\WTQNELc@Fa@DmBJs@@aF_@]?a@CYDyCt@]FO@wBMmAGgBd@iFnAGq@eB^cAPaFl@iC\\?l@mBXoIpBODJWAUC[OaAEg@Aa@?g@FwB@qBiLgEkCy@_GcBWGWEc@JYCEASKWWMKIOqD}DSSs@k@w@e@kG}CyAdDIEoGiDhAmCsNwHOGQAWAOyC}BNY?UGuAq@aGeDFOmGiDy@jB_HwD}@vBuN_Iw@pBk@lA]h@QKaDvHoE_COt@]bC{@tGi@jDKZKTMP_@`@sBzAwEfAsA?{Fo@?_AAGIIPiABIDG}@S|@REFCHQhAHH@F?~@zFn@rA?vEgArB{A^a@LQJUJ[h@kDz@uG\\cCNu@DUpE`CxCcHPJ\\i@j@mAv@qBtN~H|@wBtGpDv@kBxGnDGN`GdDtAp@TFX?|BONxCV@P@NFrNvHiAlCnGhDvAgDvGdDv@d@r@j@RRpD|DHNLJVVRJD@XBb@KVDVF~FbBjCx@~K`EfA^r@PlCh@x@LlA^bCz@nBp@xDk@bASn@O|HqBNd@h@JpBJvBLNA\\GxCu@XE`@B\\?`F^r@AlBK`@Eb@GDMPOVUf@]XOVGlAg@l@Kh@G`E?v@@l@KnCo@pE}@`BQPCNGbB}@b@U^Xn@r@FNJh@BFBBVLx@\\XNZVt@p@PPTVR\\XbAFXRx@Jt@BJDFFBj@Jp@Fj@Jn@LfBPVFJDFHJ\\FJFDxAd@VJVJNLLPXj@Vt@\\dBDNFFH@NAh@GNEJGZOXI~@G|@CdABfA?h@DHDXXJDJ@lBCp@@J@HBFDFHPj@N^JJNJd@^nBxIj@pCp@|D\\|BLrATvCNtBh@fLHfAb@jHl@nI^zEJ|Cn@`L^nE`@~IJv@h@bCDZB~@A`@u@vFGl@CtCH|J@VAl@D`FLAWxES~F?PBh@lB\\`Ch@fBTf@@J?tBOtAMZM`@OXIf@IA\\@d@BXJx@HNJH~AnAFR@ZCP|@HJ?H?VMBf@JrATxABDF@x@BElEtKI~JEHCHGbAR`@JNHHJDLDVx@nC?THDJFLDPBfAFRBNBLDNLLLX\\j@|@FFLDjAHjBFP@TDlB`@^Fl@DNBLD|B~@r@VVNJJrCbDZVJDJBL@`BIh@?NBPDzAt@z@d@^VfCfCr@j@p@b@^TRHXD|@FTBTF^NrF~CnD`CxBpAbDfBz@v@fD`DLNLPFPh@INb@PVVP\\P~Bt@f@XrA|@|@h@~@v@RJrAjAHDDFt@n@`@f@`@`@vDdCRRt@`AzBlB`Al@`Br@x@NfBNmAnO[`HCz@DHPDxF^pAFG|AQjBGpAAP@HDFVHrE|@v@R`AZ^RTF`AAz@EdC?ZCEf@BJBFb@VF@H?LG`@SLAL?b@JJHZHHEPCh@EFVHPLTJF`@Hb@r@q@PGh@FVJVn@BTLLf@Fn@CV|@@`COlGMdCKlCO~@AjBG|@?d@FtGl@pCj@t@HvCd@zCl@h@HZAVE~DbDz@z@RFXXv@r@a@vHK~@SlAxNpB^\\bAt@n@RxGbBnGzA|Ad@^RhBn@~FtAnLtClFxA^D|Ec@dEeAlCGfAIlBGLGlD@VFj@GDSbDdAtCx@bHhBH?DD?BfPvDpBf@vBj@`FxAxFzAxGhBFLxAfAjG|GVf@XQj@l@RJVBP?LEPMBRBJrEzByAtDORGDI@xA`@nAXZD^BpACRDPBhDMv@EFVDXDnAiA`@xBnJxC~F`AjC~AjATDXt@z@dF~UeA\\CzEA|BCHGBSb@Cj@Vf@TbANXjDnNy@nBOtAfF~@tDj@|@rAy@`K~Zn@|B`HlTZv@DFHBtCn@vEr@h@LJ@`Ep@xLzBdDr@`Dh@hIdBfI~AjI|A|NzCjIzB~KvDrG~BLNPNLH|H~CdIxCfBgFxA^^T|CtAfC|@|L|EHY~G`CfLxEn@gB`Bt@lAf@tEdAVBH@zAEtAGlCWzCO`BBxB@lDFnANRExDKp@?HDnBBpACvBG~EEd@?\\APCFCVUXOBGPM^Er@Gv@Sj@WlBk@d@IP@`COv@Ml@QlBs@pAk@XSRKNQx@]d@Mj@Gd@A^@FDX?\\@n@AzAInCQlBUlA[rDgArBk@p@SPKLEfAc@~CoA\\Ox@Oz@Ep@?|AFvC@rAFd@EnCGYyEAS^Dj@@@PJ~Dd@H`@APAZEbBKn@Kl@m@JNLDvDK~BCpCPx@h@b@^h@|@l@\\TNTTTXPDLIB?FB\\NPJBFl@V@?DCHGPDD?\\ApABT?NAVKPKCELIBD~BvD^j@l@`AtBtClHlIDADBBB@FADABdClCl@lACbJDXFVxC_Af@GjBCfGLb@Bt@DVHxAv@dAr@bBrAf@ZZBx@RnA`@Jv@b@~BbExArC~@lDjANDjBX`BFlAF|BZ`AJnCB`@Cx@f@bA?fBXfA`@x@n@PP~AdAn@r@bArAK`AXr@ZL^\\NR?fADh@?~@Ch@Gb@SdA~DaA~BMTnB@pDChB`IP",
        team_member_id: 2,
        team_member_name: "second driver",
        total_distance_meters: 87568,
        total_duration_seconds: 62260,
      },
      {
        stops: [
          {
            job_id: 2,
            stop_type: "job",
            arrival_time: "2025-12-02T13:56:07",
            latitude: 37.7749,
            longitude: -122.4194,
          },
          {
            job_id: 6,
            stop_type: "job",
            arrival_time: "2025-12-02T14:46:02",
            latitude: 37.7849,
            longitude: -122.4094,
          },
          {
            job_id: 5,
            stop_type: "job",
            arrival_time: "2025-12-02T18:48:45",
            latitude: 37.7649,
            longitude: -122.4294,
          },
        ],
        vehicle_id: 3,
        route_polyline:
          "kzfkCawnyLyGOF[PMnAWFC@IOo@i@kBYqACOAU?O@_@XEhGeH_DiC{C_Fu@{@Uu@rAy@fAi@f@YzAu@fA]~@a@PCYm@Tu@Bo@Uk@bAsBz@{DL{@\\uCHcAkAQf@}CRq@SSa@c@OUOIOi@KcBI_@Qo@IKEGSKKADe@CMw@_AIOAMAMBM@EV_@BMBOKSYs@IgAGyCBo@I_C@UCyBRsANyAiE[sBW_BIu@uJi@FeAyDaBl@Ou@kAeEI]CUC}AM{DAeGImCB@b@SVG}AaJ}DsTkFuXs@}CmGeRkBuEm@KYAUi@Ue@dKuGbYqQfFeDVj@bFrLl@nAfCtD`BtBxApBnBrCxAlBhAExCUtCuAzBs@nB?hBW|@IlAZjAf@bAdAvBnAvAf@~@^dBoHBS`DD\\ARL?G@CDC@U`ELLcEBcBF{AL@fAHnAHp@ABsAHiAhAaC|CwEjByGbBgOAcC[mF@_Hb@uDd@qC`DsMqBm@`BkF`BqHx@m@pCaCp@yCFmD@qE]cHMaFkA_LaAgC_B}CcB{EV_DNsEr@_FNkBFkDAuCEmAYeCaAgCGaB[}Bk@oC[uAU_DB[GmCF{C?uCc@{DKmCMkCW_Do@qB@Y~A_AOu@vFaCm@qB@{Au@Xs@RmCmIGIyAwDg@b@g@w@IODm@FG@UfC{QoBBUMWuBEMKEqEVW?OGM_@i@}E_AeGa@H[FEkAC_@Mw@QgCGM]YyBqBaBaBa@e@g@{@NU@UEOe@y@l@_@s@sCK@}B}K_@wAsC|@c@uAEAGI]}Ao@gCUo@]Ts@kBkAaDgAiCYm@AG@GN]f@_ARa@dCgE^i@Z_@vCeHjA}Cp@cBhBwCj@w@~AoFjAiENk@XcBrCh@d@LhATQjAPkAiAUe@MsCi@YbBOj@kAhE_BnFeAa@mDeBkFq@oASIRSd@MTSXgB~BwAtBmB`CiAnA}@t@yBbBoAjAw@h@uBAgOSS@i@?_@IeMYgDMsXs@eAAKG[Bm@Bi@CAFW|DQfAI\\@VuAfJiBbKi@zDO`BStCg@nGExAB`FYjG@tA@zFKfFCbCSRoATc@JoHxCYRM^C^?dBClAEVSVYFe@@{C?wBFUrEIlBe@Ck@BsABq@YCRoAzEqBjEa@Ar@vC@LuAKeFaAg@hC}CDQdBGx@Kj@o@jBgAjCUDe@EmASaB[wCk@w@GU@a@CwCK}AFqAF}@\\oAj@oAb@gCx@A}@e@DSHs@DkAFMoCoHPGB]BCDA@G?ECg@@KCcD?_DMkB?iBIsASeA[sBu@s@e@{Ac@aAKcAAsA\\QJ?FCBA@E??BLfBAj@C\\YFoC\\g@d@MOmA^DlAeBO}Ck@YhCq@xAaAfBqBUQxAUdASL?XDFa@~AUz@EbAI`@[tAN?_@f@gA|@g@TIQ_AB{FSeDD_@fDWbCCz@@x@DhDEd@Ot@El@u@bY?NExCAzBH\\R`@DXPr@Fn@EPVbGDbFj@nEsAVyCl@cCZOBoBNoH\\GHe@JA@CBG?EEWBKEiDGaC[w@QkA_@eAm@aB?k@Gi@Mi@Ey@CkABG?YSeBsAuEzF_CeCeCuBsC^m@FEFQCSBwAb@}HnA]`@y@jAc@f@m@vAw@nAy@jAm@v@u@x@i@f@cAx@QFk@P_Cn@_Bd@}Ah@sDrAeBh@kAZkBb@KT}@`Ao@r@u@r@q@t@g@z@Sl@Il@Ch@Bb@FL?RGPMDIAQ?_@J{AdD]j@kAlBo@n@kA`BSf@Kd@Bt@?PANEFE@ICMMMMS?QFUVkEdH{LpUa@l@OBYAyB[CbAGtAE~BEDGBEACCCG?CBGBCFADBBB@B?HEDGBEACCCG_@OeCqAyF_D_EmCqDeDsJeHqFsEaG{EmG}EkAp@uNgMOUCMm@Hw@Bo@IkDl@yDh@iBXsAVw@Eg@FcHhAoAX{@j@kAXuAPqB`@a@JgDdAiAV_ABsAb@uBfAcEbDiBnAyAjAcA`AqBdCgAnAiG|GmAdBI^o@fDIn@a@`Bc@xAg@{@sASkCg@IoAgAA?MaBMFaAeBK{@Y}@LcAKm@Uc@Gy@PmBd@uDl@mHdAaD\\k@Jk@\\EKsCn@sLfAcCJmAI}CpMy@nDcPaEC@G?CACGs@SiGyAyBq@cDeAy@o@[QcBgCy@o@m@_@m@OgA@aL^}CNq@Cy@Mu@Ys@a@k@q@oA}BuAsBo@s@yAmAmAgAw@e@wAs@cBm@kCo@cEg@g@CwB@yBNsAJwC^}Dj@{@D}@Ae@I_ASo@Wc@We@a@mCqCWUI_@{@{@_EcDWD[@i@I{Cm@wCe@u@IqCk@uGm@e@G}@?kBF_A@mCNeCJmGLaCN}@ABWGo@Mg@UMo@CKWGWFi@p@Qc@s@a@IKGMUIQGWi@DQBID[IKIc@KM?M@a@RMFI?GAc@WCGCKDg@[BeC?{@DaA@UG_@SaA[w@SsE}@WIEGAI@QFqAPkBF}AqAGyF_@QEEIB{@ZaHlAoOgBOy@OaBs@aAm@{BmBu@aASSwDeCa@a@a@g@u@o@EGIEsAkASK_Aw@}@i@sA}@g@Y_Cu@]QWQQWOc@i@HGQMQMOgDaD{@w@cDgByBqAoDaCsF_D_@OUGUC}@GYESI_@Uq@c@s@k@gCgC_@W{@e@{Au@QEOCi@?aBHMAKCKE[WsCcDKKWOs@W}B_AMEOCm@E_@GmBa@UEQAkBGkAIMEGGk@}@Y]MMOMMEOCSCgAGQCMEKGIE?Uy@oCEWEMIKOIa@KcASIFIB_KDeLHDmEi@CGACEUyAKsACg@WLI?K?}@IBQA[GS_BoAKIIOKy@CYAe@@]g@HYHa@N[LuALuBNK?g@AgBUaCi@mB]M?C_@A_@XoHHaDHAEaF@m@AWI}JBuCFm@t@wF@a@C_AE[i@cCKw@a@_J_@oECg@k@yJK}C_@{Em@oIc@kHIgAi@gLOuBUwCMsA]}Bq@}Dk@qCoByIe@_@OKKKO_@Qk@GIGEICKAq@AmBBKAKEYYIEi@EgA?eAC}@B_AFYH[NKFODi@FO@IAGGEO]eBWu@Yk@MQOMWKqBq@GEGKK]GIKEWGgBQo@Mk@Kq@Gk@KGCEGCKKu@Sy@GYYcAS]UWQQu@q@[WYOy@]WMCCCGKi@GOo@s@_@Yc@TcB|@OFQBaBPqE|@oCn@m@Jw@AaE?i@Fm@JmAf@WFYNg@\\WTQNELc@Fa@DmBJs@@aF_@]?a@CYDyCt@]FO@wBMmAGgBd@iFnAGq@eB^cAPaFl@iC\\?l@mBXoIpBODJWAUC[OaAEg@Aa@?g@FwB@qBiLgEkCy@_GcBWGWEc@JYCEASKWWMKIOqD}DSSs@k@w@e@kG}CyAdDIEoGiDhAmCsNwHOGQAWAOyC}BNY?UGuAq@aGeDFOmGiDy@jB_HwD}@vBuN_Iw@pBk@lA]h@QKaDvHoE_COt@]bC{@tGi@jDKZKTMP_@`@sBzAwEfAsA?{Fo@?_AAGIIPiABIDG}@S|@REFCHQhAHH@F?~@zFn@rA?vEgArB{A^a@LQJUJ[h@kDz@uG\\cCNu@DUpE`CxCcHPJ\\i@j@mAv@qBtN~H|@wBtGpDv@kBxGnDGN`GdDtAp@TFX?|BONxCV@P@NFrNvHiAlCnGhDvAgDvGdDv@d@r@j@RRpD|DHNLJVVRJD@XBb@KVDVF~FbBjCx@~K`EfA^r@PlCh@x@LlA^bCz@nBp@xDk@bASn@O|HqBNd@h@JpBJvBLNA\\GxCu@XE`@B\\?`F^r@AlBK`@Eb@GDMPOVUf@]XOVGlAg@l@Kh@G`E?v@@l@KnCo@pE}@`BQPCNGbB}@b@U^Xn@r@FNJh@BFBBVLx@\\XNZVt@p@PPTVR\\XbAFXRx@Jt@BJDFFBj@Jp@Fj@Jn@LfBPVFJDFHJ\\FJFDxAd@VJVJNLLPXj@Vt@\\dBDNFFH@NAh@GNEJGZOXI~@G|@CdABfA?h@DHDXXJDJ@lBCp@@J@HBFDFHPj@N^JJNJd@^nBxIj@pCp@|D\\|BLrATvCNtBh@fLHfAb@jHl@nI^zEJ|Cn@`L^nE`@~IJv@h@bCDZB~@A`@u@vFGl@CtCH|J@VAl@D`FLAWxES~F?PBh@lB\\`Ch@fBTf@@J?tBOtAMZM`@OXIf@IA\\@d@BXJx@HNJH~AnAFR@ZCP|@HJ?H?VMBf@JrATxABDF@x@BElEtKI~JEHCHGbAR`@JNHHJDLDVx@nC?THDJFLDPBfAFRBNBLDNLLLX\\j@|@FFLDjAHjBFP@TDlB`@^Fl@DNBLD|B~@r@VVNJJrCbDZVJDJBL@`BIh@?NBPDzAt@z@d@^VfCfCr@j@p@b@^TRHXD|@FTBTF^NrF~CnD`CxBpAbDfBz@v@fD`DLNLPFPh@INb@PVVP\\P~Bt@f@XrA|@|@h@~@v@RJrAjAHDDFt@n@`@f@`@`@vDdCRRt@`AzBlB`Al@`Br@x@NfBNmAnO[`HCz@DHPDxF^pAFG|AQjBGpAAP@HDFVHrE|@v@R`AZ^RTF`AAz@EdC?ZCEf@BJBFb@VF@H?LG`@SLAL?b@JJHZHHEPCh@EFVHPLTJF`@Hb@r@q@PGh@FVJVn@BTLLf@Fn@CV|@@`COlGMdCKlCO~@AjBG|@?d@FtGl@pCj@t@HvCd@zCl@h@HZAVE~DbDz@z@RFXXv@r@a@vHK~@SlAxNpB^\\bAt@n@RxGbBnGzA|Ad@^RhBn@~FtAnLtClFxA^D|Ec@dEeAlCGfAIlBGLGlD@VFj@GDSbDdAtCx@bHhBH?DD?BfPvDpBf@vBj@`FxAxFzAxGhBFLxAfAjG|GVf@XQj@l@RJVBP?LEPMBRBJrEzByAtDORGDI@xA`@nAXZD^BpACRDPBhDMv@EFVDXDnAiA`@xBnJxC~F`AjC~AjATDXt@z@dF~UeA\\CzEA|BCHGBSb@Cj@Vf@TbANXjDnNy@nBOtAfF~@tDj@|@rAy@`K~Zn@|B`HlTZv@DFHBtCn@vEr@h@LJ@`Ep@xLzBdDr@`Dh@hIdBfI~AjI|A|NzCjIzB~KvDrG~BLNPNLH|H~CdIxCfBgFxA^^T|CtAfC|@|L|EHY~G`CfLxEn@gB`Bt@lAf@tEdAVBH@zAEtAGlCWzCO`BBxB@lDFnANRExDKp@?HDnBBpACvBG~EEd@?\\APCFCVUXOBGPM^Er@Gv@Sj@WlBk@d@IP@`COv@Ml@QlBs@pAk@XSRKNQx@]d@Mj@Gd@A^@FDX?\\@n@AzAInCQlBUlA[rDgArBk@p@SPKLEfAc@~CoA\\Ox@Oz@Ep@?|AFvC@rAFd@EnCGYyEAS^Dj@@@PJ~Dd@H`@APAZEbBKn@Kl@m@JNLDvDK~BCpCPx@h@b@^h@|@l@\\TNTTTXPDLIB?FB\\NPJBFl@V@?DCHGPDD?\\ApABT?NAVKPKCELIBD~BvD^j@l@`AtBtClHlIDADBBB@FADABdClCl@lACbJDXFVxC_Af@GjBCfGLb@Bt@DVHxAv@dAr@bBrAf@ZZBx@RnA`@Jv@b@~BbExArC~@lDjANDjBX`BFlAF|BZ`AJnCB`@Cx@f@bA?fBXfA`@x@n@PP~AdAn@r@bArAK`AXr@ZL^\\NR?fADh@?~@Ch@Gb@SdA~DaA~BMTnB@pDChB`IP",
        team_member_id: 2,
        team_member_name: "second driver",
        total_distance_meters: 87568,
        total_duration_seconds: 62260,
      },
    ],
    status: "success",
    generated_at: "2025-12-01T13:59:00.641824",
    optimization_goal: "minimum_time",
    unassigned_job_ids: [],
    total_distance_meters: 87568,
    total_duration_seconds: 62260,
  },
  created_at: "2025-12-01T19:28:22.414157+05:30",
  updated_at: "2025-12-01T19:29:00.675123+05:30",
};
